version: '3'

vars:
  MVN: ./scripts/mvnw

tasks:
  default: 
    desc: list all comands
    cmds: 
      - task -l

  # -----------------------------
  # Comandos principales
  # -----------------------------
  
  run:
    desc: Run Spring Boot application
    cmds:
      - "{{.MVN}} spring-boot:run"

  test:
    desc: Run all tests
    cmds:
      - "{{.MVN}} test"

  build:
    desc: run deploy containers
    cmds:
      - "{{.MVN}} clean package"
      - cp target/*.jar build/
      - docker compose -f build/compose.yml up


  clean:
    desc: Clean build artifacts
    cmds:
      - "{{.MVN}} clean"

  # -----------------------------
  # Docker & base de datos
  # -----------------------------
  up:
    desc: Start Docker containers
    cmds:
      - docker compose up -d

  down:
    desc: Stop Docker containers
    cmds:
      - docker compose down

  db:
    desc: open NAME
    cmds:
      - docker exec -it aros_db bash -c 'mariadb -p$DB_ROOT_PASSWORD'

  reset_db:
    desc: Reset NAME containers and volumes
    cmds:
      - docker compose down -v
      - docker compose up -d
